export type Resume = {
  name: string;
  currentDesignation?: string;
  standardizedDesignation?: string;
  overview?: string;
  totalExperience?: string;
  industryNormalizedExperience?: string;
  avgExperiencePerCompany?: string;
  longestExperience?: string;
  recentExperience?: string;
  technicalSkills?: string[];
  domainSkils?: string[];
  keyProjects?: string;
  id?: string;
  questionsToBeAsked?: string[];
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  createdBy?: string;
  createdDate?: string;
};
