export type Resume = {
  name: string;
  currentDesignation?: string;
  standardizedDesignation?: string;
  overview?: string;
  totalExperience?: string;
  industryNormalizedExperience?: string;
  avgExperiencePerCompany?: string;
  longestExperience?: string;
  recentExperience?: string;
  technicalSkills?: any;
  domainSkills?: any;
  keyProject?: string;
  id?: string;
  questionsToBeAsked?: any;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  createdBy?: string;
  createdDate?: string;
};
